#!/bin/bash

# Copyright (C) 2010-2011 Ulteo SAS
# http://www.ulteo.com
# Author Samuel BOVEE <samuel@ulteo.com> 2010-2011
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; version 2
# of the License
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

# check needed tools
tools="aclocal libtoolize autoheader autoconf automake libtool"
for tool in $tools; do
  which $tool > /dev/null || (echo "error, install $tool" && exit 1)
done

# get version
if [ -n "$OVD_VERSION" ]; then
    version="$OVD_VERSION"
else
    if [ -d .svn ]; then
      revision=$(LC_ALL=C svn info . | awk '/^Revision: / {printf "%05d\n", $2}')
    else
      revision=0
    fi
    version="99.99.svn$revision"
fi

sed -e "s/@VERSION@/${version}/g" < configure.ac.in > configure.ac
sed -e "s/@VERSION@/${version}/g" < setup.py.in > setup.py

autoreconf -fvi && ./configure $@
