#!/bin/bash
# Copyright (C) 2010 Ulteo SAS
# http://www.ulteo.com
# Author David Lechevalier <david@ulteo.com>
#
# This program is free software; you can redistribute it and/or 
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; version 2
# of the License
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

CHANNEL_APPLICATION=$1
CHANNEL_ARGS=$2
USER=$3
DISPLAY=$4
PRIVILEGE=$5
APPLICATION="${CHANNEL_APPLICATION} ${CHANNEL_ARGS} ${USER}"


echo "channel app : ${CHANNEL_APPLICATION}"
echo "argument : ${CHANNEL_ARGS}"
echo "user : ${USER}"
echo "display : ${DISPLAY}"
echo "privilege : ${PRIVILEGE}"

if [ "${PRIVILEGE}" = "root" ]; then
	echo "${APPLICATION}"
	export DISPLAY=${DISPLAY} && ${APPLICATION}
else
	echo "su - ${PRIVILEGE} -c '${APPLICATION}'"
	su - ${PRIVILEGE} -c "export DISPLAY=${DISPLAY} && ${APPLICATION}"
fi

echo "fin"



